name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    name: Linux Build
    strategy:
      matrix:
        cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make CC=${{ matrix.cc }}
  
  macos-build:
    name: MacOS Build
    strategy:
      matrix:
        cc: [ gcc-13, clang ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make CC=${{ matrix.cc }}
